version: '3'

services:
  
  # Первый шард
  shard1_primary:
    image: mongo:latest
    container_name: shard1_primary
    restart: always
    ports:
      - "27021:27017"
    volumes:
      - shard1-primary-data:/data/db
    command:
      [
        "mongod", 
        "--shardsvr", 
        "--replSet", 
        "rs_shard1", 
        "--bind_ip_all", 
        "--port", 
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh","--port", "27017", "--eval", "db.runCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 15s
      retries: 3

  shard1_secondary1:
    image: mongo:latest
    container_name: shard1_secondary1
    restart: always
    ports:
      - "27022:27017"
    volumes:
      - shard1-secondary1-data:/data/db
    command:
      [
        "mongod", 
        "--shardsvr", 
        "--replSet", 
        "rs_shard1", 
        "--bind_ip_all", 
        "--port", 
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh","--port", "27017", "--eval", "db.runCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 15s
      retries: 3

  shard1_secondary2:
    image: mongo:latest
    container_name: shard1_secondary2
    restart: always
    ports:
      - "27023:27017"
    volumes:
      - shard1-secondary2-data:/data/db
    command:
      [
        "mongod", 
        "--shardsvr", 
        "--replSet", 
        "rs_shard1", 
        "--bind_ip_all", 
        "--port", 
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh","--port", "27017", "--eval", "db.runCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 15s
      retries: 3

  # Второй шард
  shard2_primary:
    image: mongo:latest
    container_name: shard2_primary
    restart: always
    ports:
      - "27024:27017"
    volumes:
      - shard2-primary-data:/data/db
    command:
      [
        "mongod", 
        "--shardsvr", 
        "--replSet", 
        "rs_shard2", 
        "--bind_ip_all", 
        "--port", 
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh","--port", "27017", "--eval", "db.runCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 15s
      retries: 3

  shard2_secondary1:
    image: mongo:latest
    container_name: shard2_secondary1
    restart: always
    ports:
      - "27025:27017"
    volumes:
      - shard2-secondary1-data:/data/db
    command:
      [
        "mongod", 
        "--shardsvr", 
        "--replSet", 
        "rs_shard2", 
        "--bind_ip_all", 
        "--port", 
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh","--port", "27017", "--eval", "db.runCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 15s
      retries: 3

  shard2_secondary2:
    image: mongo:latest
    container_name: shard2_secondary2
    restart: always
    ports:
      - "27026:27017"
    volumes:
      - shard2-secondary2-data:/data/db
    command:
      [
        "mongod", 
        "--shardsvr", 
        "--replSet", 
        "rs_shard2", 
        "--bind_ip_all", 
        "--port", 
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh","--port", "27017", "--eval", "db.runCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 15s
      retries: 3

  # Сервер конфигурации
  configSrv:
    image: mongo:latest
    container_name: configSrv
    restart: always
    ports:
      - "27027:27017"
    volumes:
      - config-data:/data/db
    command:
      [
        "mongod", 
        "--configsvr", 
        "--replSet", 
        "config_server", 
        "--bind_ip_all", 
        "--port", 
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh","--port", "27017", "--eval", "db.runCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 15s
      retries: 3

  # Роутеры
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    depends_on:
      - configSrv
      - shard1_primary
      - shard2_primary
    ports:
      - "27028:27017"
    command:
      [
        "mongos", 
        "--configdb", 
        "config_server/configSrv:27017", 
        "--bind_ip_all", 
        "--port", 
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh","--port", "27017", "--eval", "db.runCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 15s
      retries: 3

  # API приложение
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27017"
      MONGODB_DATABASE_NAME: "mongodb1"

volumes:
  config-data:
  shard1-primary-data:
  shard1-secondary1-data:
  shard1-secondary2-data:
  shard2-primary-data:
  shard2-secondary1-data:
  shard2-secondary2-data: